DASKMS_PARTITION_KEY = "__daskms_partition_schema__"
ARROW_METADATA = "__daskms_arrow_metadata__"
DASKMS_METADATA = "__daskms_metadata__"
CASA_KEYWORDS = "__casa_keywords__"
DASKMS_PARQUET_VERSION = "0.0.1"
